version: '3'
services:
   db:
     image: mariadb:latest
     volumes:
       - db_data:/var/lib/mysql
       - ../db_data/latest.sql:/docker-entrypoint-initdb.d/latest.sql
     restart: always
     env_file: .env
   wordpress:
     depends_on:
       - db
     build: .
     env_file: .env
     ports:
       - "8888:80"
     restart: always
     volumes:
       - ../wordpress/wp-content:/var/www/html/wp-content
       - ../wordpress/.htaccess:/var/www/html/.htaccess
   mailhog:
      image: mailhog/mailhog:v1.0.0
      ports:
        - "1025:1025"
        - "8025:8025"
volumes:
    db_data:

